# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Kotlin
kotlin.code.style=official

# Mod Properties
mod_version = 1.4.0-beta1
mod_id = weatherchanger
maven_group = me.lucaslah.weatherchanger
archives_base_name = weather-changer

# Minecraft Properties
minecraft_version=26.1
java_version=25

# Fabric
fabric_loom_version=1.15.5
fabric.loader_version=0.18.5
fabric.version=0.145.1+26.1

# Forge
forge_gradle_version=[7.0.17,8)
forge.version=26.1-62.0.9
mixin_gradle_version=0.7.+
mixin_version=0.8.5