name: Build

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build
        run: ./gradlew build

      - name: Compute Build Identifier
        id: commit_short_sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Find Build Artifacts
        run: |
          mkdir -p artifacts
          
          find . -type d -path '*/build/libs' | while read -r dir; do
            project_name=$(basename "$(dirname "$(dirname "$dir")")")
            mkdir -p "artifacts/$project_name"
            cp -r "$dir"/* "artifacts/$project_name/"
          done

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: 'WeatherChanger-${{ steps.commit_short_sha.outputs.sha_short }}'
          path: 'artifacts/'